New component for search system
TYPO3-Documentation/render-guides pull request #851
Opened 2024-11-27 16:10 UTC by cregourd

Integration of a new component for search system. This component is made by using React, Vite JS is used to bundle all React component into bundle.

- [x] Still possible to use plain HTML with the old system (no javascript enabled)
- [x] Use ViteJs for bundling
- [x] Allow multiple scoping levels for search

> ⚠️ This component is currently not functional because it requires a change to the  `search/suggest` API endpoint. All suggested packages must have a slug to redirect to the pre-filled search page.

2024-11-28 12:30 UTC, linawolf commented
When you make changes to the templates please run 

```
make integration-baseline
```
to make the tests pass

2024-11-28 12:58 UTC, tlenclos requested changes

2024-11-28 12:58 UTC, tlenclos commented on packages/typo3-docs-theme/resources/js/components/GlobalSearch.jsx
> +    }, []);
```suggestion
useEffect(() => {
    const globalSearchInput = document.getElementById('globalsearchinput');

    if (globalSearchInput) {
        globalSearchInput.addEventListener('click', handleInputClick);
        return () => {
            globalSearchInput.removeEventListener('click', handleInputClick);
        };
    }
}, []);
```

2024-11-28 13:25 UTC, damienalexandre commented on packages/typo3-docs-theme/resources/public/fonts/fa-brands-400.ttf
As you can see, Font Awesome was not up to date with the version in packages.json.

```diff
- * Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com
+ * Font Awesome Free 6.7.0 by @fontawesome - https://fontawesome.com
```

So this PR contains the font update + CSS.

Should we split this in two PR or is it ok? @linawolf

2024-11-28 13:25 UTC, damienalexandre commented on packages/typo3-docs-theme/resources/js/components/SearchModal.jsx
> +    }, []);
We miss something here.

In suggestions, we need the manual_slug, to build proper contextualized urls.

2024-11-28 13:25 UTC, damienalexandre commented on packages/typo3-docs-theme/resources/js/components/SuggestRow.jsx
> +                <p className="suggest-row__title">{title}</p>
We may need to add an ellipsis here for long titles on mobile.

2024-11-28 13:25 UTC, damienalexandre commented on packages/typo3-docs-theme/resources/js/hooks/useSearchSuggestions.js
> +                href: `http://localhost:300°/${result.manual_slug}/${result.relative_url}#${result.fragment}`,
This needs to be replaced.

2024-11-28 16:05 UTC, linawolf commented on packages/typo3-docs-theme/resources/public/fonts/fa-brands-400.ttf
This is fine I think

2024-12-03 16:42 UTC, damienalexandre commented on packages/typo3-docs-theme/resources/js/components/SearchModal.jsx
> +    }, []);
Done :white_check_mark:

2024-12-03 16:49 UTC, linawolf approved these changes

2024-12-03 16:49 UTC, merged